### ISSUE TITLE
Trailing slash on directory= leads to cryptic errors

### ISSUE THREAD

**Issue by Veyrdite** [tenox7/wfm#36]
I was often getting an HTML error dialog from wfm when trying to view or work with files in certain directories:

> Basename path too short

Other files & dirs would work fine, and I think this problem _might_ be made worse by symlinks.

I modified the relevant code in wfm.c to provide me more info:

if(strlen(dirname(temp_dirname)) < strlen(cfg.homedir)) 
        error("Basename path too short.  temp_dirname:'%s' cfg.homedir:'%s'", temp_dirname, cfg.homedir);

This spat out the answer:

> Basename path too short. temp_dirname:'/home/abcd/site/public' cfg.homedir:'/home/abcd/site/public/'

:(

Removing the trailing slash from my directory=asdf line in my wfm config fixed this problem.

**Suggested solutions**

(1) Make error messages show the evidence of why there is an error, rather than just claiming there is one cryptically.  ie print out the strings that were compared.

(2) Warn the user not to end their directory=xxx in a slash via a comment in the config file or a message at runtime (the former is probably enough).

... OR ...

(3) Silently strip away any slashes at the end of directory=xxx on loading.

**Comment by tenox7** [comment]
Hi thank you for the bug report. You seem to have coded it already. Why don't you send a PR? Thank you!
